spring.application.name=CloudNotebookTest
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_notebook_db
spring.datasource.username=notebook_user
spring.datasource.password=Ameko26356
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true